### ISSUE TITLE
We could raise an error if Formtastic is not configured

### ISSUE THREAD

**Issue by justinfrench** [formtastic/formtastic#1118]
ActiveAdmin and other gems list formtastic as a dependency, but don't force the developer to run our installer, which sets up a the configuration file. This has lead to a lot of confusion for deprecation errors when upgrading to Formtastic 3.1 and not really having an awareness that formtastic has a configuration they may need to manage.

So, I think we could add a new hook in our initializer that signals to Formtastic that it has been explicitly configured with an initializer, so that all users have a complete install. We could probably also ping AA and other libraries to run our installer as part of their install and upgrade processes.

**Comment by seanlinsley** [comment]
Is there a list of deprecation errors somewhere that 3.1 introduces, that will be an issue when missing the configuration file?

**Comment by seanlinsley** [comment]
CC @timoschilling

**Comment by timoschilling** [comment]
For new installs activeadmin can trigger the formtastic install, for old installs formtastic should warn.

**Comment by justinfrench** [comment]
@seanlinsley see [DEPRECATIONS](https://github.com/justinfrench/formtastic/blob/master/DEPRECATIONS)
