### ISSUE TITLE
Symbols support is incomplete

### ISSUE THREAD

**Issue by romanbsd** [formtastic/formtastic#1127]
While using with the role_model gem, the following inconsistency has surfaced:
- The user.roles returns a Set of Symbols
- The User.valid_roles is an array of Symbols

While the selected_values (make_selected_values) is an array of Symbols, the Collections#collection converts the User.valid_roles to array of strings because

``` ruby
[Array, Fixnum, String].include?(raw_collection.first.class) #-> false
```

As a workaround, I provide the collection in the form:

``` ruby
User.valid_roles.map { |role| role.to_s.humanize }.zip(User.valid_roles)
```

**Comment by justinfrench** [comment]
Sounds like we can treat symbols like strings. Would love to see a patch!

**Comment by romanbsd** [comment]
I'm not familiar with the formtastic internals, thus I don't have a slightest idea what can break if the Symbol is added to the list above.

**Comment by Morred** [comment]
I gave this a try, so now arrays of symbols won't be mapped anymore but will be returned in their original form just like an array of strings would be. If that's not what you were aiming for here, I'm open for suggestions :)

**Comment by justinfrench** [comment]
@Morred @romanbsd could one of you confirm that the #1160 patch fixes this issue?

**Comment by Morred** [comment]
In combination with the gem @romanbsd was mentioning?

**Comment by justinfrench** [comment]
@Morred yeah, the fix _looks_ good, but I'd love to know for sure this fixes the problem it attempts to solve before merging.

**Comment by Morred** [comment]
@justinfrench Absolutely, that makes sense. I'd love for @romanbsd to try it out because he could definitely tell whether it solves the problem in his current app or not. If he doesn't have time, I'll set up a small test app and check it myself.

**Comment by justinfrench** [comment]
@romanbsd? @Morred?

**Comment by Morred** [comment]
Ah damn, completely forgot about this one! If @romanbsd isn't here anymore, I guess I'll have to be the one to try it out
