### ISSUE TITLE
We should fallback to StringInput for unknown column types

### ISSUE THREAD

**Issue by justinfrench** [formtastic/formtastic#1146]
When trying to find the most suitable input type for a given attribute, we often look to the type of database field. The current implementation doesn't have a fallback, which means we're constantly playing catch-up to add explicit mappings for column types that ActiveRecord supports.

If you have a database column type of `foo`, our fallback is to try `FooInput` if there's no explicit mapping, leading to an `unknown input` exception.

Here's the relevant code:

``` ruby
# default is a :string, a similar behaviour to Rails' scaffolding.
def default_input_type(method, options = {}) # @private
  if @object
    return :select  if reflection_for(method)

    return :file    if is_file?(method, options)
  end

  if column = column_for(method)
    # Special cases where the column type doesn't map to an input method.
    case column.type
    when :string
      return :password  if method.to_s =~ /password/
      return :country   if method.to_s =~ /country$/
      return :time_zone if method.to_s =~ /time_zone/
      return :email     if method.to_s =~ /email/
      return :url       if method.to_s =~ /^url$|^website$|_url$/
      return :phone     if method.to_s =~ /(phone|fax)/
      return :search    if method.to_s =~ /^search$/
      return :color     if method.to_s =~ /color/
    when :integer
      return :select    if reflection_for(method)
      return :select    if enum_for(method)
      return :number
    when :float, :decimal
      return :number
    when :datetime, :timestamp
      return :datetime_select
    when :time
      return :time_select
    when :date
      return :date_select
    end

    # Try look for hints in options hash. Quite common senario: Enum keys stored as string in the database.
    return :select    if column.type == :string && options.key?(:collection)
    # Try 3: Assume the input name will be the same as the column type (e.g. string_input).
    return column.type
  else
    return :select    if options.key?(:collection)
    return :password  if method.to_s =~ /password/
    return :string
  end
end
```

The problem is this line:

``` ruby
return column.type
```

I think this needs to be `return :string`, but before that happens, we'd need to ensure we have explicit mappings from any column types we know about (anything previously caught by `return column.type`), so that `StringInput` is the fallback, instead of `WhateverInput`.

Here's the replacement code with one line change and a TODO for where the extra mappings would go:

``` ruby
# default is a :string, a similar behaviour to Rails' scaffolding.
def default_input_type(method, options = {}) # @private
  if @object
    return :select  if reflection_for(method)

    return :file    if is_file?(method, options)
  end

  if column = column_for(method)
    # Special cases where the column type doesn't map to an input method.
    case column.type
    when :string
      return :password  if method.to_s =~ /password/
      return :country   if method.to_s =~ /country$/
      return :time_zone if method.to_s =~ /time_zone/
      return :email     if method.to_s =~ /email/
      return :url       if method.to_s =~ /^url$|^website$|_url$/
      return :phone     if method.to_s =~ /(phone|fax)/
      return :search    if method.to_s =~ /^search$/
      return :color     if method.to_s =~ /color/
    when :integer
      return :select    if reflection_for(method)
      return :select    if enum_for(method)
      return :number
    when :float, :decimal
      return :number
    when :datetime, :timestamp
      return :datetime_select
    when :time
      return :time_select
    when :date
      return :date_select
    # TODO add explicit mappings to all known column types that we support here
    # when :x
    #   return :y
    # when :y
    #   return :z
    end

    # Try look for hints in options hash. Quite common senario: Enum keys stored as string in the database.
    return :select    if column.type == :string && options.key?(:collection)

    # Fallback to :string if we don't explicitly handle this `column.type`
    return :string
  else
    return :select    if options.key?(:collection)
    return :password  if method.to_s =~ /password/
    return :string
  end
end
```

Anyone interested in working up a patch?

cc @timoschilling @mitio

**Comment by mitio** [comment]
Will this prevent people from the possibility to define a custom input type, say `InetInput`? If so, can it first check if there is a constant which defines the given input type and if so, to just keep it as its original type?

**Comment by timoschilling** [comment]
I think there is a better solution, currently there need's to be two implementations to get the wanted behavior, but in future where `input_class_with_const_defined` and `input_class_by_trying` are removed and only `NamespacedClassFinder` exist we need to change `NamespacedClassFinder#resolve` to return the fallback instead of `raise Formtastic::UnknownInputError`.

**Comment by justinfrench** [comment]
@mitio, to support inet in your app, you'd define  custom input and use it with `:as => :inet`. This method only deals with handling defaults when `:as` is not used, and this bug only comes up when we don't have a built in support for a given column type.

**Comment by jclay** [comment]
I'm currently running into this issue with an column of type INET. I suspect this is happening for every devise user as well. I'm happy to create a patch out of your suggestion, @justinfrench.

Before I start - @timoschilling do you mind clarifying your thoughts for implementing a better solution?

**Comment by mikz** [comment]
I was thinking about this for quite some time. The way of extending the mapping of column => input type is pretty hardcoded in formtastic itself. Some people want to map a column to different input type (#1165, #1143). Some people want a default (#1183). Some would like to have an override (#1187).

What about encoding the whole [`default_input_type`](https://github.com/justinfrench/formtastic/blob/2f8b987ee4880c4aa06e6ec799eafe48fa46e316/lib/formtastic/helpers/input_helper.rb#L254-L297) as a mapping of `type => matcher` ?

Formtastic 4.0 would be a good time to introduce such a thing. I imagine it as something like:

```
Formtastic::FormBuilder.column_mapping[:string] = { country: [/country/] }
Formtastic::FormBuilder.column_mapping[:string][:password] << /matcher/
Formtastic::FormBuilder.column_mapping.default = :string
```

`Formtastic::FormBuilder.column_mapping` would be a hash, where keys are column types and values 
are hashes where columns are input types and values are matchers. The matchers could be strings, regexps, procs.

It could rely on Ruby primitives like Hash#default to provide default values. Or just set it to own objects and handle resolving dynamically.

Just food for thought.

**Comment by mikz** [comment]
I made a prototype that is using an object to resolve inputs. Check https://github.com/mikz/formtastic/commit/1dea758937bd6b270da20c3bc7991c28c2fc6a66

I tried the "hash" approach, but it didn't work very well. Using custom objects is much easier and nicer.

Only thing I'm not very happy is that the default is done by doing `Input#match_type(nil)`. That allows matching against non existing column.

**Comment by justinfrench** [comment]
@mikz interesting! I was going to comment on the commit direct, but maybe it'd be better to create a Pull Request so we can discuss it there?

**Comment by mikz** [comment]
@justinfrench done! https://github.com/justinfrench/formtastic/pull/1211

the description is not perfect, hope to improve it in a day
