### ISSUE TITLE
Move to formtastic/formtastic

### ISSUE THREAD

**Issue by justinfrench** [formtastic/formtastic#1199]
At some point, it feels like this project should moved from justinfrench/formtastic to something more community owned. I've already created the @formtastic org many years ago.

How do we transition? What are the things to watch-out for when doing this? Anyone had experience?

**Comment by mikz** [comment]
Github maintains redirect when the repository is renamed. I just tested and it works even when the repository is transferred to an organization.

**Comment by seanlinsley** [comment]
I moved Active Admin from gregbell/active_admin to activeadmin/activeadmin a few years back. The issues I ran into were:
- the links to old Travis CI builds no longer worked: https://github.com/travis-ci/travis-ci/issues/2698
- Codetriage had two different pages for Active Admin: https://github.com/codetriage/codetriage/issues/405

**Comment by justinfrench** [comment]
Have made this change 🎉
