### ISSUE TITLE
polymorphic associations

### ISSUE THREAD

**Issue by kvokka** [formtastic/formtastic#1213]
My question is here https://stackoverflow.com/questions/36632607/formtastic-activeadmin-polymorphic-associations

I saw some commits about it, but there is mo mansion in readme or somewhere else, how to use.
Or there is no such feature?

**Comment by mikz** [comment]
Thanks for the report. I'd like to take a look at it. Do you mind creating a sample repo reproducing the case? It looks quite complex and it would allow us to make a test case for it.

**Comment by kvokka** [comment]
Thank you for answer.
I've made update in SO post, so the part of problem solved. But anyway, I did not found any mansion about polymorphic associations, so i spent all day for digging. You may use my SO post as a template, i will be pleased is it useful :)
