### ISSUE TITLE
Safari autofilling email / password fields

### ISSUE THREAD

**Issue by habermeier** [formtastic/formtastic#1222]
I'm using formtastic through activeadmin, and we have a situation where an admin may edit all fields of a user record, such as email and password.  Safari is being insistent on pre-filling out email field, overriding a perfectly good pre-filled input with the user's own email.  auctomopelte=off is ignored.

There are some workarounds: http://stackoverflow.com/questions/22817801/how-to-disable-auto-fill-in-safari-7  -- similar to other suggestions that go all the way back to 2014.  The basic idea is to include fake email / password fields that are offscreen.

All those solutions require silliness that I could implement with HTML by hand easily enough, but given this generates all that for me, it's unclear how I could create those fields off-screen.  Especially "hard" for me through activeadmin.  I'll post there as well, but figured I'd just ask here as well.

This is the cross post: https://github.com/activeadmin/activeadmin/issues/4480#issuecomment-226962810

**Comment by justinfrench** [comment]
Hi there,

I can give you guidance on how to generate extra hidden fields using Formtastic, but I'm not 100% sure how they'll apply to ActiveAdmin, as I don't use it.

So a super basic Formtastic form is this:

```
<%= semantic_form_for @user do |f| %>
  <%= f.inputs %>
  <%= f.actions %>
<% end %>
```

That will automatically detect which fields, and how to render them. However, you should specify the exact fields you want, and what kind of input is rendered for each field:

```
<%= semantic_form_for @user do |f| %>
  <%= f.inputs do |f| %>
    <%= f.input :name, :as => :string %>
    <%= f.input :email_address, :as => :email %>
  <% end %>
  <%= f.actions %>
<% end %>
```

In your case, it seems like you want to add extra HTML to the form (hidden fields). The good news is that this is just ERB, so you can do that:

```
<%= semantic_form_for @user do |f| %>
  <!-- your extra HTML here -->
  <%= f.inputs do |f| %>
    <!-- your extra HTML here -->
    <%= f.input :name, :as => :string %>
    <%= f.input :email_address, :as => :email %>
  <% end %>
  <%= f.actions %>
  <!-- your extra HTML here -->
<% end %>
```

The problem I think you _might_ have is that ActiveAdmin doesn't specify it's forms with ERB. They've [added a DSL on top of Formtastic](http://activeadmin.info/docs/5-forms.html) which might make this harder for you. It does look like some pseudo-HTML is allowed (there's an `li` and a `para` in the above linked example).

So maybe you'll be able to add some custom HTML and/or CSS through ActiveAdmin's DSL to add the hidden fields you want. Have a go at that first. 

If that doesn't work, I think you still have heaps of choices or possibilities. For example…

* You could create your own [custom versions of the inputs](https://github.com/justinfrench/formtastic#creating-new-inputs-based-on-existing-ones) you need (e.g. `:as => :autofill_safari_hack_email`).
* You could possibly utilise the built-in `:as => :hidden` input
* You could possibly add custom inline styles using `:wrapper_html => { :style => "…" }` and/or `:input_html => { :style => "…" }`

There are examples of all of these in the README, though I'm not 100% sure how well each will translate to ActiveAdmin, and I'm not 100% sure exactly what HTML/solution you're aiming for. If all of those fail, I can think of some even more elaborate work-arounds, but I'll wait to here back from you.
