### ISSUE TITLE
Handling STI in generic form

### ISSUE THREAD

**Issue by bsylvain** [formtastic/formtastic#1225]
I have a generic form (new and edit) handling STI. I want the form to always use the parent controller.

I have a working form but it feels a little hacky  (final version would probably involve an helper) : 

```
semantic_form_for [:backend,@good_strategy],
                  url: (@good_strategy.new_record? ? backend_good_strategies_path : backend_good_strategy_path(@good_strategy)), 
                  as: :good_strategy do |f|
```

Is there a way to do this without the ternary operator?

**Comment by mikz** [comment]
Why this does not work with plain formtastic ? Does this work with plain rails?
