### ISSUE TITLE
Add support for Rails 5.1 form_with tags

### ISSUE THREAD

**Issue by JeremyEllingham** [formtastic/formtastic#1246]
https://github.com/rails/rails/issues/25197

Currently upgrading to Rails 5.1 breaks all the automatic styling of semantic_form_for.

Could we add a semantic_form_with tag that follows the new conventions?

**Comment by mikz** [comment]
That would be nice, but someone has to define what does not work and how it should work. Preferably with examples. Then anyone could contribute that code.
