### ISSUE TITLE
Any plans to support more than just label/value pairs in collection options?

### ISSUE THREAD

**Issue by obie** [formtastic/formtastic#1249]
Ideally instead of accepting just an array of tuples like `[['Justin', 2], ['Kate', 3]]` we could pass in an array of hashes with attributes matching `OPTION` attributes. This would enable additional functionality on options like setting disabled and accessibility attributes.

Happy to whip up a patch if wanted.

**Comment by mikz** [comment]
And those hashes would look like how? 

We already support grouped options: https://github.com/justinfrench/formtastic/blob/6953db82c96f1bc3742408073f70361b89e73652/spec/inputs/select_input_spec.rb#L502-L521
So this would be something else right? Hashes having `:value`, `:disabled` and other html attributes?

**Comment by vfonic** [comment]
`:disabled` would definitely be nice. That's what I'm trying to achieve in my app rn.

**Comment by vfonic** [comment]
Hey @justinfrench, is it possible to achieve this somehow now?

I believe @obie was suggesting something like this:

```rb
f.input :author, as: :select, collection: [{ option: 'Justin', value: 2 }, { option: 'Kate', value: 3, disabled: true }]
```

Thanks!

**Comment by justinfrench** [comment]
Hi @vfonic, to the best of my knowledge, we haven't implemented this — I was just closing off a bunch of stale issues to give the project a bit of a fresh start. Your use case looks valid and is something I'd be open to supporting, but I don't have the time to invest in preparing a patch. Perhaps you could have a go?

**Comment by vfonic** [comment]
@justinfrench thanks for the clarification!

I'm not working on anything that needs this functionality right now. If I do end up needing this again, I'll give it a go.

@obie are you still interested in making a PR for this?
