### ISSUE TITLE
How to customize the template used in `rails generate formtastic:form`?

### ISSUE THREAD

**Issue by kewlar** [formtastic/formtastic#1251]
How to override the form template used when generating `formtastic:form`?

The `rails generate formtastic:form` command uses `<formtastic_gem_dir>/lib/generators/templates/_form.html.haml`, and I couldn't find the way to override that.

I tried modifying the template `lib/templates/haml/scaffold/_form.html.haml` (that was generated with `formtastic:install`), but it seems to be used only when calling `rails generate scaffold` (as far as I could tell, it overrides the default `<haml-rail_gem_dir>/lib/generators/haml/scaffold/templates/_form.html.haml`).

---

My gem versions:

```
rails 5.1.3
haml 5.0.2
haml-rails 1.0.0
formtastic 3.1.5
```

**Comment by mikz** [comment]
I don't know but you can check the form generator https://github.com/justinfrench/formtastic/blob/master/lib/generators/formtastic/form/form_generator.rb
and investigate how it is supposed to use the template path and verify that it is doing it correctly.
