### ISSUE TITLE
Input for PostgreSQL array datatype

### ISSUE THREAD

**Issue by nicolas-brousse** [formtastic/formtastic#1254]
Hi,

I'm currently using an [`array` datatype](http://edgeguides.rubyonrails.org/active_record_postgresql.html#array) on a model but I don't know how to manage it with formtastic.

I would like to manage an array of string as a nested form.

**Example**

```ruby
create_table :posts do |t|
  t.string :title
  t.text :body
  t.string :tags, array: true, null: false, default: []
end
```
With this is example I expect to remove, add, update a tag.

How could I do it?

Thanks

**Comment by mikz** [comment]
How you want to present it to the user? String input like `one, two, three` ? Or checkboxes? 
Formtastic provides input types for collections. See the Readme.

**Comment by nicolas-brousse** [comment]
In this case, a list of string input and a "add more" button to add an empty input to add more tags.  
I'm not looking to add relation datas or datas that already exists on DB.

**Comment by nicolas-brousse** [comment]
Something more or less like http://jsfiddle.net/jaredwilli/tZPg4/4/ or http://formvalidation.io/examples/adding-dynamic-field/#adding-fields-with-same-names.

**Comment by mikz** [comment]
@nicolas-brousse formtastic does not provide any javascript widgets for adding more inputs. Only predefined collections. They don't have to be relations - readme shows collection with strings.

You can create our own input or try to find 3rd party inputs. Guess Active Admin has some for this.

**Comment by nicolas-brousse** [comment]
@mikz thanks for your answer. The javascript part is not really the problem, I can do it. It's more how to manage it with `formtastic`.

> They don't have to be relations - readme shows collection with strings

True, I just meant that I would like a free input, where user can write everything he want.

May be I could have an input like `<input type="text" name="post[tags][]" />` and duplicate it with some javascripts.

I searched on Active Admin but I found nothing for now.

**Comment by mikz** [comment]
@nicolas-brousse if you want one free form input then just provide an attribute on the model that is a string and manages the serialization/deserialization from the array. Like act-as-taggable tag_list method: https://github.com/mbleigh/acts-as-taggable-on

**Comment by nicolas-brousse** [comment]
@mikz I start working on a custom input https://gist.github.com/nicolas-brousse/f4530e466c71f909e758c1817032cd39. I take inspiration from https://gist.github.com/franks921/44509c65da3bea99bc49.

I try to do something generic.
