### ISSUE TITLE
Better support for polymorphic fields

### ISSUE THREAD

**Issue by dkniffin** [formtastic/formtastic#1264]
Right now, there's no easy way to set up a field for a polymorphic association. There's [a helpful error message](https://github.com/justinfrench/formtastic/blob/ec0b090de764f09cd7d68177ac6fea9011d907b4/lib/formtastic/inputs/base/collections.rb#L77) that says `A collection must be supplied for #{method} input. Collections cannot be guessed for polymorphic associations.` However, in addition to setting up a collection, you have to handle the `_type` part of the association.

In my app, I've got two models, `Activity` and `Document`. Activities have the association `belongs_to :trackable, polymorphic: true` (they're used to track if a user has viewed a document for example).

In activeadmin, I've just created a form for this. The `:trackable` field was easy to set up with the `collection` key. In this specific case, it was easy to just set the `trackable_type` field via a hidden input, because I only ever need to set a `Document` on this field.

```rb
  form do |f|
    f.inputs do
      f.input :user
      f.input :trackable, collection: Document.all
      f.input :trackable_type, as: :hidden, input_html: { value: "Document" }
    end
    actions
  end
```

A better solution to build into formtastic though would be that if a polymorphic field is given a `collection` option, to set it up an associated `_type` field automatically, based on the values from that collection.

Then, I could just do the following, and the type would be inferred:

```rb
  form do |f|
    f.inputs do
      f.input :user
      f.input :trackable, collection: Document.all
    end
    actions
  end
```

**Comment by mikz** [comment]
@dkniffin I get the point, but don't see how to do this without JavaScript. 

Formtastic could get several types in the collection and then would need to send two inputs - one for the id and other for the type and need a way to sync them somehow.

For your case of just one type per input I'd say it is easier to define `document_id=` on the model that basically does just `self.trackable = Document.find(id)` and rest will be handled by Rails.

**Comment by dkniffin** [comment]
@mikz What if we did something like what's described [here](https://github.com/activeadmin/activeadmin/wiki/Nested-forms-with-polymorphic-association-in-Active-Admin-Formtastic#other-possibility-would-be), and set up the field so that the values are actually a combination of the type and the id, then interpret that correctly in the controller?

**Comment by mikz** [comment]
@dkniffin I think this is not a decision for formtastic to take.

It would not work out of the box because it needs a change in the model. And I don't think it is very nice solution because it would not work with UUID ids for example.

**Comment by letiesperon** [comment]
Did someone find a clean way around this?
