### ISSUE TITLE
ruby 2.7 support

### ISSUE THREAD

**Issue by seb-sykio** [formtastic/formtastic#1308]
hi,
I try to update to ruby 2.7.1 but I have thousands of warning
formtastic-3.1.5/lib/formtastic/localizer.rb:118: warning: deprecated Object#=~ is called on FalseClass; it always returns nil

formtastic-3.1.5/lib/formtastic/i18n.rb:26: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

**Comment by mikz** [comment]
I believe that was fixed by https://github.com/justinfrench/formtastic/pull/1307

**Comment by seb-sykio** [comment]
thanks, any idea about a release date ? ;-)

**Comment by mikz** [comment]
Yeah, that's not a priority for some time already. I'd recommend using it as git dependency.
Master is very stable anyway.

**Comment by seb-sykio** [comment]
thanks, I tried but them formtastic-bootstrap gem is not working anymore
       ActionView::Template::Error:
         uninitialized constant Formtastic::Util
       # gems/formtastic-bootstrap-3.1.1/lib/formtastic-bootstrap/helpers/fieldset_wrapper.rb:26:in `field_set_and_list_wrapping'

and this gems is not maintain anymore. Do you know any replacement maybe ?

thanks again for your help

**Comment by mikz** [comment]
I'm not using formtastic-bootstrap, sorry. Maybe you can fork it and change it? `Formtastic::Util` was a recent removal in https://github.com/justinfrench/formtastic/commit/cbbff9c76645be2548f9f6350f5b4b832c4616f0#diff-307fa8c47fcf4e3139e823dd839b7efe

You can also create that module in your project.

**Comment by peterdeweese** [comment]
Maintainers, we really need a release for various other gems to point to and for direct use. What is the hold-up and how can I help?

**Comment by justinfrench** [comment]
I've cut a 4.0.0.rc1 gem today, and am enlisting new maintainers. Closing.

**Comment by gsar** [comment]
@justinfrench this issue is not fixed by #1307 as @mikz stated incorrectly above. #1307 fixed a different deprecation warning, not the one being reported here. please reopen.
