### ISSUE TITLE
Migrating from justinfrench/formtastic to formtastic/formtastic

### ISSUE THREAD

**Issue by justinfrench** [formtastic/formtastic#1312]
Hi everyone, just noting some changes I've made lately to ensure that this repo and gem isn't reliant on me as a maintainer.

Ownership and contributors:

* I converted the `formtastic` user (which I had previously registered) into an org
* The current owner of the formtastic org is me, @justinfrench, but I'm actively looking for new maintainers and a new owner
* I transferred the repo from justinfrench/formtastic to formtastic/formtastic
* I invited all previous maintainers (plus @deivid-rodriguez) to the formtastic org (I also removed them as outside contributors)

Linked services:

* In #1311 I updated a bunch of URLs and links, mostly in the README, which meant I needed to… 
* Set up a new formtastic/formtastic RDoc https://rdoc.info/projects/formtastic/formtastic
* Set up a new formtastic/formtastic Travis CI https://travis-ci.org/formtastic/formtastic
* Set up a new formtastic/formtastic CodeClimate https://codeclimate.com/github/formtastic/formtastic

New 4.0 release:

* I published a 4.0.0.rc1 gem today
* I cleaned up a bunch of stale issues, branches, milestones, etc — so we're starting pretty fresh
* @deivid-rodriguez has been cleaning up master, will help release the final 4.0.0 and address any issues that come up afterwards

Gem publishing:

* @mikz and I have permission to publish new gems
* I'll be looking to add @deivid-rodriguez as a publisher next

If you notice anything else that is dependent on me, would like to join as a maintainer (and possibly even take over ownership of the project), please open an issue!

**Comment by jakemiller13** [comment]
Hello - what is the status of this Gem? Is it still being maintained by @justinfrench or @deivid-rodriguez (or anyone else)? There are some outstanding PRs and I am curious if they will be merged or if we need to implement a monkey patch on our end. Thank you.

**Comment by jakemiller13** [comment]
Got it, thanks very much for the info @mikz !
