### ISSUE TITLE
Gem release supporting Ruby 3.0

### ISSUE THREAD

**Issue by norman** [formtastic/formtastic#1325]
Hello,

We recently added Ruby 3.0 to our CI matrix in order to discover any incompatibilities ahead of upgrading in a few months.

It's not urgent for us yet, but we noticed that the current gem release of Formtastic doesn't work with the i18n gem because of Ruby 3's change in how keyword arguments work. Your master branch does already have the changes necessary and works properly Ruby 3.0, so changing our dependency to the master branch rather than the gem temporarily solves the problem for us.

Since Formtastic is a dependency of Active Admin I doubt I'm the only person currently affected by this. I just wanted to call it to your attention since this is such a mature library now that it no longer gets frequent releases, but I think it might be a good idea to push an update out reasonably soon.

Thanks for your work on this gem over the many years I've been using it.

**Comment by ogirginc** [comment]
@norman beat me by 8 minutes. :)

**Comment by deivid-rodriguez** [comment]
Yeah, formtastic 4 is long due. I'll try to coordinate a final release :+1:.

**Comment by norman** [comment]
Thank you for pushing out the release @deivid-rodriguez! I'll close this issue now.
